### ISSUE TITLE
Can't find files 'train_pdb_keys.list', 'eval_pdbs_keys.list', and 'test_pdb_keys.list'

### ISSUE THREAD

**Issue by cclough** [alexechu/protpardelle#2]
I'm having trouble finding these files - maybe they are right in front of me though! 'train_pdb_keys.list', 'eval_pdbs_keys.list', and 'test_pdb_keys.list'

Thanks for the great paper and repo!

**Comment by alexechu** [comment]
Ah yes you have to make them yourself, something like `ls -l > train_pdb_keys.list` and maybe some editing after. It should be pretty flexible so if you wanted to train on your own dataset, you'd just have to supply PDB files and designate their split by making these list files. Thanks for trying it out!
